id: I3EAD5731
ocr_import_info:
  timestamp: '2023-09-28T04:49:42.933278+00:00'
  batch_id: batch-320c
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharma Kyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-28 06:35:19.981738+00:00
last_modified: 2023-09-28 06:35:19.981745+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1CZ1190
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1CZ1190
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དཀོན་མཆོག་གསུམ་ལ་བསྟོད་པའི་འགྲེལ་པ།
  languages:
  - bo
  author: བླ་མ་དམ་པ་བསོད་ནམས་རྒྱལ་མཚན།
statistics:
  ocr_word_mean_confidence_index: 0.8958313254362417
  ocr_word_median_confidence_index: 0.9563434
bases:
  I1CZ1652:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1CZ1652
      total_pages: 8
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1CZ1652.txt
    statistics:
      ocr_word_median_confidence_index: 0.9563434
      ocr_word_mean_confidence_index: 0.8958313254362417
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
